# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Collara' do
  platform :ios, '7.0'
  pod 'SocketRocket'
  pod 'FontAwesomeKit/IonIcons'
  pod 'DateTools'
  pod 'NJKWebViewProgress'
  pod 'JSQMessagesViewController'
  pod 'ECSlidingViewController', :path => '~/Documents/workspace/ECSlidingViewController/'
  #pod 'ECSlidingViewController', '~> 1.3'
  pod 'SignalR-ObjC', :path => '~/Documents/workspace/SignalR-ObjC/'
  #pod 'SignalR-ObjC', '2.0.0.alpha1'
  pod 'CRToast', '~> 0.0.7'
  pod 'MBProgressHUD', '~> 0.8'
  pod 'Objective-C-Generics'
end

target 'CollaraTests' do

end

