# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Collara' do
  platform :ios, '7.0'
  pod 'SocketRocket'
  pod 'FontAwesomeKit/IonIcons'
  pod 'DateTools'
  pod 'NJKWebViewProgress'
  pod 'JSQMessagesViewController'
  pod 'ECSlidingViewController', :git => 'https://github.com/ECSlidingViewController/ECSlidingViewController.git'
  pod 'SignalR-ObjC', :path => '~/Documents/workspace/SignalR-ObjC/'
  pod 'MBProgressHUD'
  pod 'Objective-C-Generics'
  pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip.git'
  pod 'BOZPongRefreshControl'
  pod 'Masonry'
  pod 'TPKeyboardAvoiding', :git => 'https://github.com/wonderxboy/TPKeyboardAvoiding.git'
  pod 'XLForm'
  pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
  pod 'MagicalRecord'
end

target 'CollaraTests' do

end

